/**
 * article → DVH 数字人视频 bridge. PR #57 fire-and-forget 模式复用.
 * 流程: 去重 → 取 article → 抽 narration → real 失败 fallback mock → 持久化 contents (type=video)
 */
import { and, eq, sql } from "drizzle-orm";
import type { db as dbType } from "../../models/db.js";
import { contents } from "../../models/schema.js";
import { initialStatusFields } from "../articles/state-machine.js";
import { logger } from "../../config/logger.js";
import { isRealMode } from "./client.js";
import { submitDvhTask } from "./submit-task.js";
import { queryDvhTaskUntilDone } from "./query-task.js";
import { getMockDvhFixture } from "./mock-fixture.js";
import { TEMPLATE_AVATAR_VOICE_MAP, type TemplateId } from "./template-mapping.js";

export interface DvhBridgeOptions {
  db: typeof dbType;
  tenantId: string;
  userId: string;
  articleContentId: string;
  templateId: TemplateId;
  conversationId?: string | null;
  journalId?: string;
}

function extractNarration(title: string, body: string | null): string {
  const plain = (body || "").replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim();
  return `${title}。${plain.slice(0, 80)}。`.slice(0, 200);
}

async function produceVideo(text: string, title: string, templateId: TemplateId, tenantId: string) {
  if (!isRealMode()) {
    const m = getMockDvhFixture(templateId);
    return { ...m, realMode: false };
  }
  try {
    const submit = await submitDvhTask({ text, templateId, tenantId, title });
    const query = await queryDvhTaskUntilDone(submit.taskUuid);
    return { videoUrl: query.videoUrl, taskUuid: submit.taskUuid, durationMs: query.durationMs, realMode: true };
  } catch (err) {
    logger.warn({ err: err instanceof Error ? err.message : err, templateId }, "dvh.bridge.real_failed_fallback_mock");
    const m = getMockDvhFixture(templateId);
    return { ...m, realMode: false };
  }
}

export async function triggerDvhFromArticle(opts: DvhBridgeOptions): Promise<void> {
  const { db, tenantId, userId, articleContentId, templateId, conversationId, journalId } = opts;
  try {
    const existing = await db.select({ id: contents.id }).from(contents).where(and(
      eq(contents.tenantId, tenantId),
      eq(contents.type, "video"),
      sql`${contents.metadata}->>'sourceArticleId' = ${articleContentId}`,
      sql`${contents.metadata}->>'source' = 'dvh'`,
    )).limit(1);
    if (existing.length > 0) {
      logger.info({ articleContentId, existingId: existing[0]!.id }, "dvh.bridge.dedup");
      return;
    }
    const [article] = await db.select().from(contents).where(eq(contents.id, articleContentId)).limit(1);
    if (!article) {
      logger.warn({ articleContentId }, "dvh.bridge.no_article");
      return;
    }
    const title = article.title ?? "BossMate";
    const narration = extractNarration(title, article.body);
    const mapping = TEMPLATE_AVATAR_VOICE_MAP[templateId];
    const produced = await produceVideo(narration, title, templateId, tenantId);

    const [row] = await db.insert(contents).values({
      tenantId, userId,
      conversationId: conversationId ?? null,
      type: "video",
      title,
      body: produced.videoUrl,
      ...initialStatusFields("draft"),
      metadata: {
        videoUrl: produced.videoUrl,
        taskUuid: produced.taskUuid,
        durationMs: produced.durationMs,
        avatarCode: mapping.avatarCode,
        avatarLabel: mapping.avatarLabel,
        voiceCode: mapping.voiceCode,
        voiceLabel: mapping.voiceLabel,
        templateId,
        sourceArticleId: articleContentId,
        source: "dvh",
        autoGenerated: true,
        realMode: produced.realMode,
      },
    }).returning({ id: contents.id });

    logger.info(
      { articleContentId, videoContentId: row?.id, templateId, realMode: produced.realMode, journalId },
      "dvh.bridge.success",
    );
  } catch (err) {
    logger.warn(
      { err: err instanceof Error ? err.message : err, articleContentId, templateId: opts.templateId },
      "dvh.bridge.fatal",
    );
  }
}
