/**
 * article → DVH 数字人视频 bridge. PR #57 fire-and-forget 模式复用.
 * 流程: 去重 → 取 article → 抽 narration → real 失败 fallback mock → 持久化 contents (type=video)
 */
import { and, eq, sql } from "drizzle-orm";
import type { db as dbType } from "../../models/db.js";
import { contents } from "../../models/schema.js";
import { initialStatusFields } from "../articles/state-machine.js";
import { logger } from "../../config/logger.js";
import { isRealMode } from "./client.js";
import { submitDvhTask } from "./submit-task.js";
import { queryDvhTaskUntilDone } from "./query-task.js";
import { getMockDvhFixture } from "./mock-fixture.js";
import { postprocessVideoWithSubtitle } from "./video-postprocess.js";
import { TEMPLATE_AVATAR_VOICE_MAP, type TemplateId } from "./template-mapping.js";

export interface DvhBridgeOptions {
  db: typeof dbType;
  tenantId: string;
  userId: string;
  articleContentId: string;
  templateId: TemplateId;
  conversationId?: string | null;
  journalId?: string;
}

/**
 * 抽取朗读文本.
 * PR #241 (5-23): 优先 article.metadata.videoScript (AI 专为视频写的脚本, 100-150 字钩子+数据+CTA).
 *   没有 fallback 到 title + body 前 80 字 (V1 简陋兜底).
 */
function extractNarration(article: { title: string | null; body: string | null; metadata: unknown }): string {
  // PR #241 v2: 优先 videoScript (目标 90 秒视频, 250-350 字; 阈值 100 字过滤太短的兜底数据)
  const meta = article.metadata as { videoScript?: string } | null;
  const vs = meta?.videoScript;
  if (typeof vs === "string" && vs.trim().length >= 100) {
    return vs.trim().slice(0, 600);
  }
  // Fallback: 老逻辑 title + body 前 80 字
  const title = article.title ?? "";
  const plain = (article.body || "").replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim();
  return `${title}。${plain.slice(0, 80)}。`.slice(0, 200);
}

async function produceVideo(text: string, title: string, templateId: TemplateId, tenantId: string) {
  if (!isRealMode()) {
    const m = getMockDvhFixture(templateId);
    return { ...m, realMode: false };
  }
  try {
    const submit = await submitDvhTask({ text, templateId, tenantId, title });
    const query = await queryDvhTaskUntilDone(submit.taskUuid);
    // PR #252 (5-24): ffmpeg burn-in 自定义字幕 (取代 DVH 默认黑色不可改字幕).
    //   失败时 postprocessVideoWithSubtitle 内部 fallback 原 videoUrl, 不阻塞链路.
    const pp = await postprocessVideoWithSubtitle({
      videoUrl: query.videoUrl,
      subtitlesUrl: query.subtitlesUrl ?? "",
      taskUuid: submit.taskUuid,
    });
    return {
      videoUrl: pp.videoUrl,
      taskUuid: submit.taskUuid,
      durationMs: query.durationMs,
      realMode: true,
    };
  } catch (err) {
    logger.warn({ err: err instanceof Error ? err.message : err, templateId }, "dvh.bridge.real_failed_fallback_mock");
    const m = getMockDvhFixture(templateId);
    return { ...m, realMode: false };
  }
}

export async function triggerDvhFromArticle(opts: DvhBridgeOptions): Promise<void> {
  const { db, tenantId, userId, articleContentId, templateId, conversationId, journalId } = opts;
  try {
    const existing = await db.select({ id: contents.id }).from(contents).where(and(
      eq(contents.tenantId, tenantId),
      eq(contents.type, "video"),
      sql`${contents.metadata}->>'sourceArticleId' = ${articleContentId}`,
      sql`${contents.metadata}->>'source' = 'dvh'`,
    )).limit(1);
    if (existing.length > 0) {
      logger.info({ articleContentId, existingId: existing[0]!.id }, "dvh.bridge.dedup");
      return;
    }
    const [article] = await db.select().from(contents).where(eq(contents.id, articleContentId)).limit(1);
    if (!article) {
      logger.warn({ articleContentId }, "dvh.bridge.no_article");
      return;
    }
    const title = article.title ?? "BossMate";
    // PR #241: extractNarration 改签 — 传 article 让其内部判断 metadata.videoScript 优先
    const narration = extractNarration(article);
    const mapping = TEMPLATE_AVATAR_VOICE_MAP[templateId];
    const produced = await produceVideo(narration, title, templateId, tenantId);

    const [row] = await db.insert(contents).values({
      tenantId, userId,
      conversationId: conversationId ?? null,
      type: "video",
      title,
      body: produced.videoUrl,
      ...initialStatusFields("draft"),
      metadata: {
        videoUrl: produced.videoUrl,
        taskUuid: produced.taskUuid,
        durationMs: produced.durationMs,
        avatarCode: mapping.avatarCode,
        avatarLabel: mapping.avatarLabel,
        voiceCode: mapping.voiceCode,
        voiceLabel: mapping.voiceLabel,
        templateId,
        sourceArticleId: articleContentId,
        source: "dvh",
        autoGenerated: true,
        realMode: produced.realMode,
      },
    }).returning({ id: contents.id });

    logger.info(
      { articleContentId, videoContentId: row?.id, templateId, realMode: produced.realMode, journalId },
      "dvh.bridge.success",
    );
  } catch (err) {
    logger.warn(
      { err: err instanceof Error ? err.message : err, articleContentId, templateId: opts.templateId },
      "dvh.bridge.fatal",
    );
  }
}
