/**
 * Track A.2：article→video script auto-bridge。fire-and-forget；
 * 用 contents.metadata.sourceArticleId 去重；错误吞掉不影响图文流程。
 */
import { and, eq, sql } from "drizzle-orm";
import type { db as dbType } from "../../models/db.js";
import { contents } from "../../models/schema.js";
import { logger } from "../../config/logger.js";
import type { AIProvider } from "../ai/providers/base.js";
import { VideoSkill } from "./video-skill.js";
import { initialStatusFields } from "../articles/state-machine.js";

export interface AutoVideoBridgeOptions {
  provider: AIProvider;
  db: typeof dbType;
  journalId: string;
  tenantId: string;
  userId: string;
  articleContentId: string;
  conversationId?: string | null;
}

/**
 * Fire-and-forget。调用方不必 await（也可以 await 在测试里检查行为）。
 * 任何错误都吞掉，只打 log，不让 article 流程感知。
 */
export async function triggerVideoFromArticle(opts: AutoVideoBridgeOptions): Promise<void> {
  const { provider, db, journalId, tenantId, userId, articleContentId, conversationId } = opts;

  try {
    // 1. 去重：同 articleContentId 已生成过 video_script 跳过
    const existing = await db
      .select({ id: contents.id })
      .from(contents)
      .where(and(
        eq(contents.tenantId, tenantId),
        eq(contents.type, "video_script"),
        sql`${contents.metadata}->>'sourceArticleId' = ${articleContentId}`,
      ))
      .limit(1);
    if (existing.length > 0) {
      logger.info({ articleContentId, existingId: existing[0].id }, "video.auto.dedup: 跳过重复生成");
      return;
    }

    // 2. 生成 video script（V7 LLM 真数据 → 失败 fallback 6 场景）
    const skill = new VideoSkill(provider);
    const result = await skill.generateForJournal(journalId, tenantId);
    if (!result || !result.artifact) {
      logger.warn({ journalId, articleContentId }, "video.auto.failed: skill 返回空 artifact");
      return;
    }

    // 3. 持久化到 contents 表，metadata 关联 sourceArticleId
    const [row] = await db.insert(contents).values({
      tenantId, userId,
      conversationId: conversationId ?? null,
      type: result.artifact.type,
      title: result.artifact.title,
      body: result.artifact.body,
      // P0-A2：auto-video-bridge → video，statusUpdatedAt 必须有
      ...initialStatusFields("draft"),
      metadata: {
        ...(result.artifact.metadata || {}),
        sourceArticleId: articleContentId,
        autoGenerated: true,
        source: "auto-from-article",
      },
    }).returning({ id: contents.id });

    logger.info(
      { articleContentId, videoContentId: row?.id, journalId },
      "video.auto.success: article → video script bridge",
    );
  } catch (err) {
    // 严格吞错 —— article 流程不感知
    logger.warn(
      { err: err instanceof Error ? err.message : err, articleContentId, journalId },
      "video.auto.failed",
    );
  }
}
